config/routes.rb
Hospitalin::Application.routes.draw do

  devise_for :users
  root 'hospitalin#main'
  get  'public/:token', to: 'hospitalin#public_profile', as: :public_profile

  namespace :patient do
    root 'main#dashboard'
    get  'public', to: 'main#public', as: :public
  end

  namespace :doctor do
    root 'main#dashboard'
    get  'documentation', to: 'main#documentation', as: :documentation
  end

  namespace :nurse do
    root 'main#dashboard'
    resources :patients
    get  'documentation', to: 'main#documentation', as: :documentation
  end


end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :patients

  def patient?
    role == "patient"
  end

  def doctor?
    role == "doctor"
  end

  def nurse?
    role == "nurse"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout :check_layout

  def check_layout
    if user_signed_in?
      current_user.role
    else
      "application"
    end
  end
end

app/controllers/doctor/main_controller.rb
class Doctor::MainController < ApplicationController
  before_filter :authenticate_user!

  def dashboard
    @patients = Patient.all
  end

  def documentation
  end
end

app/controllers/hospitalin_controller.rb
class HospitalinController < ApplicationController
  def main
    if user_signed_in?
      if current_user.patient?
        redirect_to :patient_root
      end
      if current_user.doctor?
        redirect_to :doctor_root
      end
      if current_user.nurse?
        redirect_to :nurse_root
      end

    end
  end

  def public_profile
    public_token = params[:token]
    @user = User.find_by_public_token(public_token)
    if @user.blank?
      redirect_to root_path
    end
  end
end

app/controllers/nurse/main_controller.rb
class Nurse::MainController < ApplicationController
  def dashboard
    @patient = Patient.new
  end

  def documentation
  end
end

app/controllers/nurse/patients_controller.rb
class Nurse::PatientsController < ApplicationController
  def index
  end

  def create
    password_length = 6
    password = Devise.friendly_token.first(password_length)

    user = User.where(email: params[:patient][:email]).first_or_create!(password: 'testtest', role: 'patient', name: params[:patient][:parent], public_token: password)
    user.save!

    patient = Patient.new patient_params
    patient.user = user
    patient.save!
  end


  private
  def patient_params
    params.require(:patient).permit(:email, :diagnose_pre, :parent)
  end

end

app/controllers/patient/main_controller.rb
class Patient::MainController < ApplicationController
  before_filter :authenticate_user!

  def dashboard
  end

  def public
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctor/main_helper.rb
module Doctor::MainHelper
end

app/helpers/hospitalin_helper.rb
module HospitalinHelper
end

app/helpers/nurse/main_helper.rb
module Nurse::MainHelper
end

app/helpers/nurse/patients_helper.rb
module Nurse::PatientsHelper
end

app/helpers/patient/main_helper.rb
module Patient::MainHelper
end

app/views/doctor/main/dashboard.html.haml
.patient_page

  .day_raspisanie
    .container
      .row
        .col-xs-12.col-md-12
          %section
            %header
              %a{href: '#'} Расписание дня
            %item
              9:00 - 12:00 Обход пациентов с заведующим

  .gradient
    -##Главная навигация доктора
    .container
      .row
        .col-xs-12.col-md-12
          %section.patient_navigation
            %nav
              %ul.nav.nav-pills
                %li.active
                  %a{}
                    %span Пациенты
                %li
                  =link_to doctor_documentation_path do
                    %span Документация

    .patient_messages
      .container
        .row
          .col-md-6
            .jumbotron
              %section{style: 'display: flex; align-items: center;'}
                %h2.link_index
                  %a{href: '#'} Сообщения от пациентов
                %span{style: 'font-size: 12pt; font-style: italic; position: relative; top: 4px; padding: 0 15px'} 6 новых
              %section.patient_message
                .message
                  %span.link_show
                    %a.patient_number{href: '#'} Пациент 7832
                  %span.message_date Сегодня, в 12:34
                  .message_body
                    — Доктор, а какие продукты мне можно кушать?
                .message_reply
                  %button.action_reply.btn.btn-primary{type: "button"} Ответ
                  %button.action_later.btn{type: "button"} Отложить
                .message_form.hidden
                  %form
                    %textarea{style: 'width: 500px'}
                    %button.action_write.btn.btn-primary{type: "button"} Написать
                    %button.action_close.btn{type: "button"} Закрыть
                .reply.hidden
                  .reply_body
                    — Молочнокислые продукты, кефир, перетертый жидкий суп
              %section.next_message.hidden
                %button.btn.btn-primary{type: "button"} Следующее сообщение

    .patients
      .container
        .row
          .col-xs-12.col-md-7
            %section
              %header
                %h2 Пациенты отделения
              - @patients.each do |patient|
                .patient{style: 'display: -webkit-flex;'}
                  %div{style: 'padding-right: 45px;'}
                    .patient_if
                      = patient.parent
                      %a{href: ''}= "№ #{patient.id}"
                    .patient_number
                    .patient_diagnose
                      = patient.diagnose_pre
                  .patient_age_sex{style: 'padding-right: 35px;'}
                    29 M
                  .palata{style: 'padding-right: 35px;'}
                    %a{href: '#'} палата № 5
                    .action
                      %a{href: '#'} Перевести в другую палату
                  .medical{style: 'padding-right: 25px;'}
                    %a{href: '#'} Капельница

app/views/doctor/main/documentation.html.haml
.documentation_page
  .day_raspisanie
    .container
      .row
        .col-xs-12.col-md-12
          %section
            %header
              %a{href: '#'} Расписание дня
            %item
              9:00 - 12:00 Обход пациентов с заведующим

  .gradient
    -##Главная навигация доктора
    .container
      .row
        .col-xs-12.col-md-12
          %section.patient_navigation
            %nav
              %ul.nav.nav-pills
                %li
                  =link_to doctor_root_path do
                    %span Пациенты
                %li.active
                  %a{}
                    %span Документация

    %div{style: 'margin-top: 40px; margin-left: 45px;'}
      .container
        .row
          .col-xs-12.col-md-12
            %h2 Медицинская документация
            .documents
              .document{style: 'display: -webkit-flex;'}
                .document_icon
                  =image_tag 'pdf-icon.png', size: '20x20'
                %div{style: 'position: relative; top: 2px; margin-left: 5px;'}
                  .document_name
                    %a{href: 'https://www.dropbox.com/s/xfqqcfro4unrvvc/forma%20003_o.pdf'}
                      Медицинская карта стационарного больного
                  .document_type
                    Форма первичной учетной документации № 003/о
                  .document_size
                    (PDF, 685 КБ)

app/views/hospitalin/main.html.haml
.patient_authorization.patient_color
  -##Главная навигация медсестры
  .container
    .row
      .col-xs-12.col-md-12
        %section.select_user
          %nav
            %ul.nav.nav-pills
              %li.active.patients
                %a{}
                  %span Пациентам
              %li.doctors
                %a{}
                  %span Врачам и медработникам

    -#Форма авторизации для пациента
    .row
      .col-xs-12.col-md-5
        .patient_form
          %section.authorization
            = form_tag session_path(:user) do
              %h1.header Персональная история госпитализации
              .form-group
                %label{for: "email"}
                  Для входа или регистрации введите адресс электронной почты
                .row
                  .col-xs-11.col-md-11
                    %div{style: 'display: -webkit-flex'}
                      = text_field_tag 'user[email]', nil, placeholder: ''
                      = hidden_field_tag 'user[password]', 'testtest'
                      = hidden_field_tag 'user[remember_me]', 'yes'
                      = button_to 'Далее', nil, class: 'btn btn-primary'
                %p demo: test_1@patient.com
                %p demo: test_2@patient.com

    -#Форма авторизации для медсестры и врача
    .row
      .col-md-5
        .doctor_form.hidden
          %section.authorization
            = form_tag session_path(:user) do
              %h1.header Личный рабочий кабинет
              .form-group
                .row
                  .col-xs-11.col-md-11
                    %div{style: 'display: -webkit-flex'}
                      = text_field_tag 'user[email]', nil, placeholder: ''
                      = hidden_field_tag 'user[password]', 'testtest'
                      = hidden_field_tag 'user[remember_me]', 'yes'
                      = button_to 'Далее', nil, class: 'btn btn-primary'
                %p demo doctor: test_1@doctor.com
                %p demo doctor: test_2@doctor.com

                %p demo nurse: test_1@nurse.com
                %p demo nurse: test_2@nurse.com

app/views/hospitalin/public_profile.html.haml
.public_profile
  .status
    .container
      .row
        .col-xs-12.col-md-12
          %section
            %h2= "Публичная информация пациента <strong>#{@user.name}</strong>".html_safe
            .status_description
              %span.label.label-success
                Состояние стабильное

  .hospitalization
    .container
      .row
        .col-xs-12.col-md-12
      %section
        .current_hospitalization
          %header
            %h3
              Госпитализирован 13 декабря
            %span 3 дня назад
          .hospital{style: 'margin-top: 10px;'}
            %a{href: '#'} Октябрьская клиническая больница
            %a{href: '#'} Хирургическое отделение № 2
          .diagnose
            = "Диагноз при госпитализации: #{@user.patients.first.diagnose_pre}"


  .doctors
    .container
      .row
        .col-xs-12.col-md-12
      %section
        .current_hospitalization
          %header
            %h3
              Медицинский персонал
          %div{style: 'display: -webkit-flex; margin-top: 10px;'}
            .doctor{style: 'margin-right: 30px;'}
              %a{href: '#'} Петренко А
              %div Лечащий врач
              %div +38093 324-34-23
            .doctor{style: 'margin-right: 30px;'}
              %a{href: '#'} Семенова В
              %div Дежурная медсестра
              %div +38093 324-34-23
            .doctor
              %a{href: '#'} Автандил К
              %div Дежурный хирург
              %div +38093 324-34-23

.hospitalization
  .container
    .row
      .col-xs-12.col-md-12
    %section
      .current_medicine
        %header{style: 'margin-bottom: 20px;'}
          %h3
            Список необходимых лекарств и диагностических процедур
        .medicine{style: 'margin-bottom: 5px;'}
          .row
            .col-xs-2.col-md-2
              %div
                %a{href: '#'} Реосорбент 200мл
            .col-xs-6.col-md-1
              %div
                14 грн/шт
            .col-xs-6.col-md-1
              %div
                3 шт.
        .medicine{style: 'margin-bottom: 5px;'}
          .row
            .col-xs-2.col-md-2
              %div
                %a{href: '#'} Глюкоза 400мл
            .col-xs-6.col-md-1
              %div
                20 грн/шт
            .col-xs-6.col-md-1
              %div
                3 шт.
        .medicine{style: 'margin-bottom: 5px;'}
          .row
            .col-xs-2.col-md-2
              %div
                %a{href: '#'} Система
            .col-xs-6.col-md-1
              %div
                5 грн/шт
            .col-xs-6.col-md-1
              %div
                3 шт.
        .summa{style: 'margin-top: 10px;'}
          %h3{style: 'font-size: 16px; font-weight: bold;'} Итого 117 грн

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= analytics_init :local => Rails.env.development? %>
  <title>Hospitalin #Hack4Good 0.5</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/top_navigation' %>
<%= yield %>


</body>
</html>

app/views/layouts/doctor.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= analytics_init :local => Rails.env.development? %>
  <title>Hospitalin #Hack4Good 0.5</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/top_doctor_navigation' %>
<%= yield %>


</body>
</html>

app/views/layouts/nurse.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= analytics_init :local => Rails.env.development? %>
  <title>Hospitalin #Hack4Good 0.5</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/top_nurse_navigation' %>
<%= yield %>


</body>
</html>

app/views/layouts/patient.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= analytics_init :local => Rails.env.development? %>
  <title>Hospitalin #Hack4Good 0.5</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/top_patient_navigation' %>
<%= yield %>

</body>
</html>

app/views/nurse/main/dashboard.html.haml
.main_nurse_page

  .day_raspisanie
    .container
      .row
        .col-xs-12.col-md-12
          %section
            %header
              %a{href: '#'} Расписание дня
            %item
              8:00 - 10:00 Проветривание палат
  .gradient
    .container
      .row
        .col-xs-12.col-md-12
          %section.patient_navigation
            %nav
              %ul.nav.nav-pills
                %li.active
                  %a{}
                    %span Госпитализация
                %li
                  =link_to nurse_patients_path do
                    %span Пациенты
                %li
                  =link_to nurse_documentation_path do
                    %span Документация

    .hospitalisation
      .container
        .row
          .col-xs-12.col-md-6
            %section.hosp_form
              %header
                %h3 Госпитализация больного
              = simple_form_for [:nurse, @patient] do |patient|
                .patient_phone
                  .field
                    = patient.input :email, label: 'Имейл'
                .patient_inic
                  .field
                    = patient.input :parent, label: 'Имя Отчество'
                .patient_vozrast
                  .field
                    %label Полных лет
                    %nav
                      %ul.nav.nav-pills
                        %li
                          %a{}
                            %span 18 - 25
                        %li
                          %a{}
                            %span 26 - 35
                        %li.active
                          %a{}
                            %span 36 - 60
                        %li
                          %a{}
                            %span от 60
                    %input.hidden{type: 'text'}
                .patient_diagnos
                  .field
                    = patient.input :diagnose_pre, label: 'Диагноз при госпитализации'
                .patient_palata
                  .field
                    %label Номер палаты
                    %nav
                      %ul.nav.nav-pills
                        %li
                          %a{}
                            %span 1
                        %li.active{title: 'интенсивной терапии'}
                          %a{}
                            %span
                              .palata_number
                                2

                        %li
                          %a{}
                            %span 3
                        %li
                          %a{}
                            %span 4
                    %input.hidden{type: 'text'}
                .patient_doctor
                  .field
                    %label Лечащий врач
                    %nav
                      %ul.nav.nav-pills
                        %li.active
                          %a{}
                            %span Веревкин
                        %li
                          %a{}
                            %span Копылова
                        %li
                          %a{}
                            %span Иванов
                        %li
                          %a{}
                            %span Петров
                    %input.hidden{type: 'text'}
                .action
                  .field
                    .patient_add
                      = button_to 'Госпитализировать', nil, class: 'btn btn-primary'


    %div{style: 'margin-top: 20px; margin-left: 0px;'}
      .container
        .row
          .col-xs-12.col-md-12
            .documents
              .document{style: 'display: -webkit-flex;'}
                .document_icon
                  =image_tag 'pdf-icon.png', size: '20x20'
                %div{style: 'position: relative; top: 2px; margin-left: 5px;'}
                  .document_name
                    %a{href: 'https://www.dropbox.com/s/xfqqcfro4unrvvc/forma%20003_o.pdf'}
                      Медицинская карта стационарного больного
                  .document_type
                    Форма первичной учетной документации № 003/о
                  .document_size
                    (PDF, 685 КБ)
              .document{style: 'display: -webkit-flex;'}
                .document_icon
                  =image_tag 'pdf-icon.png', size: '20x20'
                %div{style: 'position: relative; top: 2px; margin-left: 5px;'}
                  .document_name
                    %a{href: 'https://www.dropbox.com/s/xfqqcfro4unrvvc/forma%20003_o.pdf'}
                      Заявление на обработку персональных данных
                  .document_type
                    Форма вторичной учетной документации № 27
                  .document_size
                    (PDF, 38 КБ)

app/views/nurse/main/documentation.html.haml
.documentation_nurse_page

  .day_raspisanie
    .container
      .row
        .col-xs-12.col-md-12
          %section
            %header
              %a{href: '#'} Расписание дня
            %item
              8:00 - 10:00 Проветривание палат

  .gradient
    .container
      .row
        .col-xs-12.col-md-12
          %section.patient_navigation
            %nav
              %ul.nav.nav-pills
                %li
                  =link_to nurse_root_path do
                    %span Госпитализация
                %li
                  =link_to nurse_patients_path do
                    %span Пациенты
                %li.active
                  %a{}
                    %span Документация

    %div{style: 'margin-top: 0px; margin-left: 0px;'}
      .container
        .row
          .col-xs-12.col-md-12
            %h3 Медицинская документация
            .documents
              .document{style: 'display: -webkit-flex;'}
                .document_icon
                  =image_tag 'pdf-icon.png', size: '20x20'
                %div{style: 'position: relative; top: 2px; margin-left: 5px;'}
                  .document_name
                    %a{href: 'https://www.dropbox.com/s/xfqqcfro4unrvvc/forma%20003_o.pdf'}
                      Медицинская карта стационарного больного
                  .document_type
                    Форма первичной учетной документации № 003/о
                  .document_size
                    (PDF, 685 КБ)

app/views/nurse/patients/create.html.haml
.main_nurse_page

  .day_raspisanie
    .container
      .row
        .col-xs-12.col-md-12
          %section
            %header
              %a{href: '#'} Расписание дня
            %item
              8:00 - 10:00 Проветривание палат

  .gradient
    .container
      .row
        .col-xs-12.col-md-12
          %section.patient_navigation
            %nav
              %ul.nav.nav-pills
                %li
                  =link_to nurse_root_path do
                    %span Госпитализация
                %li
                  =link_to nurse_patients_path do
                    %span Пациенты
                %li
                  =link_to nurse_documentation_path do
                    %span Документация


    .hospitalisation
      .container
        .row
          .col-xs-12.col-md-6
            %section.hosp_form
              %header
                %h3 Больной госпитализирован

              .documents
                .document{style: 'display: -webkit-flex;'}
                  .document_icon
                    =image_tag 'pdf-icon.png', size: '20x20'
                  %div{style: 'position: relative; top: 2px; margin-left: 5px;'}
                    .document_name
                      %a{href: 'https://www.dropbox.com/s/xfqqcfro4unrvvc/forma%20003_o.pdf'}
                        Медицинская карта стационарного больного № 4534
                    .document_type
                      Форма первичной учетной документации № 003/о
                    .document_size
                      (PDF, 685 КБ)

app/views/nurse/patients/index.html.haml
.patients_nurse_page
  .day_raspisanie
    .container
      .row
        .col-xs-12.col-md-12
          %section
            %header
              %a{href: '#'} Расписание дня
            %item
              8:00 - 10:00 Проветривание палат

  .gradient
    .container
      .row
        .col-xs-12.col-md-12
          %section.patient_navigation
            %nav
              %ul.nav.nav-pills
                %li
                  =link_to nurse_root_path do
                    %span Госпитализация
                %li.active
                  %a{}
                    %span Пациенты
                %li
                  =link_to nurse_documentation_path do
                    %span Документация


    .patients
      .container
        .row
          .col-xs-12.col-md-12
            %section
              %header
                %h2.link_index
                  %a{href: '#'} Пациенты отделения
              %patient
                .patient_if
                  АС
                .patient_number
                  № 35467
                .patient_diagnose
                  Обострение язвенной болезни
                .patient_age_sex
                  29 M
                .palata
                  %a{href: '#'} палата № 6
                  .action
                    %a{href: '#'} Перевести в другую палату
                .medical
                  %a{href: '#'} Капельница

app/views/patient/main/dashboard.html.haml
.day_raspisanie_patient
  .container
    .row
      .col-xs-12.col-md-12
        %section
          %header
            %a{href: '#'} Расписание дня
          %item
            8:00 - 10:00 Проветривание палат

.gradient_patient
  .container
    .row
      .col-xs-12.col-md-12
        -##Главная навигация
        %section.patient_navigation
          %nav
            %ul.nav.nav-pills
              %li.active
                %a{}
                  %span Профиль
              %li
                = link_to '#' do
                  %span Госпитализации
              %li
                %a{}
                  %span Назначения
              %li
                %a{}
                  %span Диагностика
              %li
                %a{}
                  %span Операции

  .patient_profile

    .hospitalization
      .container
        .row
          .col-xs-12.col-md-12
        %section
          %header{style: 'margin-bottom: 15px;'}
            %h2
              Госпитализация
          .current_hospitalization
            %header{style: 'margin-bottom: 10px;'}
              %h3
                Госпитализирован 9 февраля
              %span 4 часа назад
            .hospital
              %a{href: '#'} Октябрьская клиническая больница
              %a{href: '#'} Хирургическое отделение № 2
            .diagnose= "Диагноз при госпитализации: #{current_user.patients.first.diagnose_pre}"

app/views/shared/_top_doctor_navigation.html.haml
.main_navigation
  .container
    .row
      .col-xs-12.col-md-12
        %nav.navbar.navbar-default{role: "navigation", style: 'margin-bottom: 0px;'}
          = link_to root_path, class: 'navbar-brand' do
            = image_tag 'logo.png', size: '55x55', style: 'opacity: 0.7;'
            %span{style: 'position: relative; top:6px; margin-left: 10px; color: #BA2B22; font-size: 25pt; font-weight: bold'}
              Hospitalin
          %div{style: 'padding: 0 16px;'}
            %ul.nav.navbar-nav.navbar-right{style: 'color: white;'}
              %li
                %a{}= current_user.email
              %li
                = link_to 'Выйти', destroy_user_session_path, method: :delete

app/views/shared/_top_navigation.html.haml
.main_navigation
  .container
    .row
      .col-xs-12.col-md-12
        %nav.navbar.navbar-default{role: "navigation", style: 'margin-bottom: 0px;'}
          = link_to root_path, class: 'navbar-brand' do
            = image_tag 'logo.png', size: '55x55', style: 'opacity: 0.7;'
            %span{style: 'position: relative; top:6px; margin-left: 10px; color: #BA2B22; font-size: 25pt; font-weight: bold'}
              Hospitalin

app/views/shared/_top_nurse_navigation.html.haml
.main_navigation
  .container
    .row
      .col-xs-12.col-md-12
        %nav.navbar.navbar-default{role: "navigation", style: 'margin-bottom: 0px;'}
          = link_to root_path, class: 'navbar-brand' do
            = image_tag 'logo.png', size: '55x55', style: 'opacity: 0.7;'
            %span{style: 'position: relative; top:6px; margin-left: 10px; color: #BA2B22; font-size: 25pt; font-weight: bold'}
              Hospitalin
          %div{style: 'padding: 0 16px;'}
            %ul.nav.navbar-nav.navbar-right{style: 'color: white;'}
              %li{style: 'margin-right: 30px;'}
                %a{href: '#'} Хирургическое отделение №1
              %li
                %div.user_image
                  =image_tag 'sister.png', width: '44px', height: '44px'
              %li{style: 'margin-right: 20px;'}
                %a
                  %div.user_name{style: 'font-size: 14px; font-weight: bold'}= current_user.name
                  %div.user_status{style: 'opacity: 0.6'}= current_user.title
              %li
                = link_to 'Выйти', destroy_user_session_path, method: :delete

app/views/shared/_top_patient_navigation.html.haml
.main_navigation
  .container
    .row
      .col-xs-12.col-md-12
        %nav.navbar.navbar-default{role: "navigation", style: 'margin-bottom: 0px;'}
          = link_to root_path, class: 'navbar-brand' do
            = image_tag 'logo.png', size: '55x55', style: 'opacity: 0.7;'
            %span{style: 'position: relative; top:6px; margin-left: 10px; color: #BA2B22; font-size: 25pt; font-weight: bold'}
              Hospitalin
          %div{style: 'padding: 0 16px;'}
            %ul.nav.navbar-nav.navbar-right{style: 'color: white;'}
              %li
                = link_to 'Публичная страница', public_profile_path(current_user.public_token)
              %li
                %a{}= current_user.name
              %li
                = link_to 'Выйти', destroy_user_session_path, method: :delete